build_api_container:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  script:
    - apk add --no-cache py-pip
    - pip install docker-compose
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker-compose build data_labeling_api
    - docker-compose push data_labeling_api
  only:
    - master

unit_tests:
  stage: test
  image: python:3.6  
  script:
    - pip install virtualenv
    - make venv
    - . venv/bin/activate
    - make test

